version: "3.7"
services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    command:
      - redis-server
    restart: always
    ports:
      - "6379:6379"

  bot:
    build: .
    command: sh -c "python3 main.py"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis

volumes:
  redis-data:
    driver: local